baseurl = ""
languageCode = "en-us"
title = "Kamran Khawaja"

[Params]
  github = "kkhaw1"
  bitbucket = "kamrank"
  description = "Software Engineer"
  linkedin = "kamrankhawaja"
  logo = "/img/logo.png"

